#
# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '15432:5432'
    volumes:
      - /app/cvat/assets/cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always
    ports:
      - '16379:6379'

  cvat:
    container_name: cvat
    image: openvino/cvat_server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      CVAT_POSTGRES_DBNAME: 'cvat'
      CVAT_POSTGRES_USER: 'root'
      CVAT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CVAT_NUCLIO_HOST: ${CVAT_NUCLIO_HOST}
      CVAT_SHARE_URL: "Mounted from roborock_data"
      CVAT_SERVERLESS: 1
    volumes:
      - /app/cvat/assets/cvat_data:/home/django/data
      - /app/cvat/assets/cvat_keys:/home/django/keys
      - /app/cvat/assets/cvat_logs:/home/django/logs
      - /app/cvat/assets/cvat_models:/home/django/models
      - /app/disk2/roborock_data:/home/django/share:ro

  cvat_ui:
    container_name: cvat_ui
    image: openvino/cvat_ui
    restart: always
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat

  cvat_picker:
      container_name: cvat_picker
      image: cvat/picker
      restart: always
      build:
        context: ./image_picker
        dockerfile: Dockerfile.picker
      depends_on:
          - cvat
      environment:
          CVAT_HOST: ${CVAT_HOST}
      ports:
          - '18423:80'
      volumes:
          - /app/cvat/assets/cvat_data:/app/cvat/assets/cvat_data

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
      - cvat_picker
    environment:
      CVAT_HOST: ${CVAT_HOST}
    ports:
      - '8080:80'
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
